version: 2
updates:
  # Check for npm dependency updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    # Group all development dependencies together
    groups:
       dev-dependencies:
          dependency-type: "development"

  # Check for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all actions together
    groups:
       actions:
          patterns:
            - "*"
